<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add post' => '',
    'After connect with VKontakte enter code in URL: {link}' => '',
    'All operation with your social account can execute only by you!' => '',
    'Attention' => '',
    'Connect to social network' => '',
    'Content' => '',
    'Getting started' => '',
    'No one can\'t collect or post message to your account in social network!' => '',
    'Post' => '',
    'Posts' => '',
    'Record are deleted successfully!' => '',
    'Records are deleted already.' => '',
    'Remove all records' => '',
    'Social networks' => '',
    'Status' => '',
    'Submit' => '',
    'Sync with social networks' => '',
    'There\'s Yii2-SyncSocial Extension is configurated with <nobr><code>syncDelete</code> = <code>false</code></nobr>' => '',
    'There\'s an example application of extension usage for Active Record model' => '',
    'Time Created' => '',
    'Time Published' => '',
    'Time Updated' => '',
    'Update post' => '',
    'Work with Posts' => '',
    'Work with posts' => '',
    'Yii2 SyncSocial Extension' => '',
    'that means after post deleting from social network will not be deleted' => '',
    'Add sign' => '@@@@',
    'Services' => '@@@@',
    'Signs' => '@@@@',
    'Verify code' => '@@@@',
    'Your e-mail' => '@@@@',
    'all' => '@@@@',
    'month' => '@@@@',
    'today' => '@@@@',
    'week' => '@@@@',
];
